# docker compose -f docker-compose.yml up
# docker compose -f .\docker-compose.yml up -d (detached mode)
version: '3.7'
networks:
  e_learning_support:
    name: elearning_support_network
services:
  backend_app:
    container_name: elearning_support_backend
    image: elearning_support_backend:1.0.0
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
      - "TZ=Asia/Ho_Chi_Minh"
    networks:
      - e_learning_support
    build:
      dockerfile: Dockerfile
      context: elearning_support_backend
      network: e_learning_support
    ports:
      - '8088:8088' # local