# docker compose -f docker-compose.yml up
# docker compose -f .\docker-compose-aws.yml up -d (detached mode)
version: '3.7'
services:
  backend_app:
    container_name: elearning_support_backend
    image: elearning_support_backend:1.0.0
    environment:
      - "SPRING_PROFILES_ACTIVE=remote"
    build:
      dockerfile: Dockerfile
      context: elearning_support
    ports:
      - '443:8088' # AWS EC2 instance mapping port
