# docker compose -f .\docker-compose-aws.yml up -d (detached mode)
version: '3.7'
networks:
  e_learning_support:
    name: elearning_support_network
services:
  backend_app:
    container_name: elearning_support_backend
    image: elearning_support_backend:1.0.0
    volumes:
      - app_data:/root
    environment:
      - "SPRING_PROFILES_ACTIVE=remote"
      - "TZ=Asia/Ho_Chi_Minh"
    networks:
      - e_learning_support
    build:
      dockerfile: Dockerfile
      context: elearning_support
      network: e_learning_support_network
    ports:
      - '443:8088' # AWS EC2 instance mapping port (open port 8088 as custom TCP)
volumes:
  app_data:
    name: els_app_shared_data
    driver: local
